# Generated by Django 4.2.16 on 2026-06-18 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='comment',
            new_name='comments_co_created_f3c0a0_idx',
            old_name='comments_co_created_77d8cb_idx',
        ),
        migrations.RenameIndex(
            model_name='comment',
            new_name='comments_co_usernam_190f06_idx',
            old_name='comments_co_usernam_67764f_idx',
        ),
        migrations.RenameIndex(
            model_name='comment',
            new_name='comments_co_email_7ec44a_idx',
            old_name='comments_co_email_2d2846_idx',
        ),
        migrations.RenameIndex(
            model_name='comment',
            new_name='comments_co_parent__fdf1ec_idx',
            old_name='comments_co_parent__0f7f1c_idx',
        ),
    ]
